### ISSUE TITLE
Missing fuel tank cap

### ISSUE THREAD

**Issue by gilbertohasnofb** [Harald67/c150#14]
Missing fuel tank cap on the right wing:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/17272434/4a1e8a56-5696-11e6-8ef5-d677b5ff4347.png)

**Comment by Harald67** [comment]
Yes, I'm currently working on the left wing, when it's done i'll duplicate it to make the right wing.

**Comment by gilbertohasnofb** [comment]
I see, no problems! :smile:

**Comment by gilbertohasnofb** [comment]
@Harald67 Looks great! But could you make the caps a separate object than the wings? Or alternatively create some invisible hotspot around it just like in the c182s? This way I can work on the fuel dialog which can be activated by clicking on the caps.

**Comment by gilbertohasnofb** [comment]
As soon as that is done, I will take care of https://github.com/Harald67/c150/issues/28
