### ISSUE TITLE
Hole in the fuselage above the cockpit

### ISSUE THREAD

**Issue by gilbertohasnofb** [Harald67/c150#17]
There is a hole in the fuselage above the cockpit, see:

![c150-0](https://cloud.githubusercontent.com/assets/5700795/17272871/50073a1a-56a2-11e6-884b-7e3b0506191c.jpg)

**Comment by Harald67** [comment]
The correction is not perfect...

**Comment by gilbertohasnofb** [comment]
Hmm, I think the hole is still there: 

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/17456313/dd2ebb08-5bd3-11e6-946b-f92b28b9a1c0.png)
