### ISSUE TITLE
Default view point too zoomed in

### ISSUE THREAD

**Issue by gilbertohasnofb** [Harald67/c150#18]
I believe that the default view point too zoomed in. This is the default:

![c150-0](https://cloud.githubusercontent.com/assets/5700795/17272877/c1b2eb6e-56a2-11e6-82ff-2aa3f218c035.jpg)

And this is what I would suggest (FOV 76.5):

![c150-1](https://cloud.githubusercontent.com/assets/5700795/17272879/cd7ffb62-56a2-11e6-8def-edd78b6dae9c.jpg)

**Comment by gilbertohasnofb** [comment]
@Harald67 Notice how the bottom row of the basic instruments are not on the screen with our current default view. If you agree with the proposed modification, I can work on it myself.

**Comment by Harald67** [comment]
There is a problem with the fov ; I get a grey screen because the fov is not correctly initialized.
![fgfs-screen-050](https://cloud.githubusercontent.com/assets/6804046/17275263/f3c69c86-5701-11e6-91b3-5dd9bac20ff3.jpg)
Note that it happens only for the first view, the passenger view is OK.
This is with 2016.2 I think (or some random nightly after 2016.2).

**Comment by gilbertohasnofb** [comment]
This is really strange, I will check it out now.

**Comment by gilbertohasnofb** [comment]
@Harald67 I am also with 2016.2 (I use the stable release 2016.2.1) and I can't reproduce this problem. Do you have some errors in the console? This is what I have as soon as I initialize the sim:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/17275659/aae1398c-570f-11e6-83c0-658f3b9ab58f.png)

I also tested all other views, I get no grey screens with any of them.

**Comment by Harald67** [comment]
The field of view is initialized to 0.1 in the tree for the view # 0.
Note that if you specify a '--fov=something' in the parameters then the fov specified in the c150-set.xml are not used and you don't have the grey screen.

**Comment by gilbertohasnofb** [comment]
I don't understand why it's being initialized to `0.1`, for me it's reading the value that I wrote in the set file: `76.5`. Also, I am not using `--fov=<value>`, so my fov is really being set by the `c150-set.xml` file

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/Harald67/c150/pull/22
