### ISSUE TITLE
Issues with the aircraft "configuration" menu

### ISSUE THREAD

**Issue by gilbertohasnofb** [Harald67/c150#19]
Here are some issues with the aircraft "configuration" menu:
- do we really want to load the aircraft with the configuration menu opened? I find it a bit intrusive, and for people who want to do a cold start they will have to always close that menu every time they open the sim, which is very annoying
- when toggling between the ALS flashlight, the dialog automatically closes. This means that to toggle from white light to turn the light off, I need to open the dialog twice! I would say let's just not close the dialog at all when clicking on the flashlight button
- also, why all entries in the aircraft menu end with "...", such as "Configuration..." or "Immatriculation..."? I think it's obvious they will open a new dialog, and I think these "..." look out of place

**Comment by gilbertohasnofb** [comment]
@Harald67 If you agree with these points, I'd be happy to implement them myself

**Comment by Harald67** [comment]
You are right we probably don't need that dialog to be opened at each launch of the sim.
I agree we the other points too.

**Comment by gilbertohasnofb** [comment]
Ok, so I will work on it.

**Comment by gilbertohasnofb** [comment]
@Harald67 Is it all right with you if I recreate the same configuration menu but using xml instead of Nasal?

**Comment by Harald67** [comment]
Can we have that special color like the other dialogs ? ;)

I also noticed that you changed the battery charge display ; I'm afraid the display will show something near 12V even if the battery is nearly discharged.

**Comment by gilbertohasnofb** [comment]
> Can we have that special color like the other dialogs ? ;)

I am not too sure about it, I will check it out.

> I also noticed that you changed the battery charge display ; I'm afraid the display will show something near 12V even if the battery is nearly discharged.

Oh, my bad! The problem was that the battery percentage property actually does not range from 0 to 100, but rather from 0.0 to 1.0, and it wouldn't display correctly in the XML code. In that case I will need to define a new property and use a filter to convert between them.
