### ISSUE TITLE
Create fuel dialog

### ISSUE THREAD

**Issue by gilbertohasnofb** [Harald67/c150#28]
Create fuel dialog by clicking on the fuel tank caps

**Comment by Harald67** [comment]
There is now two fuel caps that you can use for clicking and that you can hide or move if you want.

![image](https://cloud.githubusercontent.com/assets/6804046/17457737/8d1855b6-5c00-11e6-95f3-6263e1caca00.png)

**Comment by gilbertohasnofb** [comment]
Thanks, that looks cool! I will work on it today
