### ISSUE TITLE
Add 3D baggage models

### ISSUE THREAD

**Issue by gilbertohasnofb** [Harald67/c150#29]
Add 3D baggage models when baggage weight above a certain threshold

**Comment by gilbertohasnofb** [comment]
@Harald67 And just confirming, the 150 does not have a baggage door, right? You just put your baggage in the back of the plane using the main door, correct?

**Comment by Harald67** [comment]
There is no baggage door, you just throw them in the back of the plane ;)
There is also an optional child seat that you can put there, but probably not very common.

![](http://www.aircraftdealer.com/dealers/d/danbowen/32864/big_89343297.jpg)

**Comment by gilbertohasnofb** [comment]
> There is no baggage door, you just throw them in the back of the plane ;)

Yes, that's what I thought :smile: Actually the 150 is the only plane I have flown, but it has been a decade since then :cry: 

> There is also an optional child seat that you can put there, but probably not very common.

I would say then to not bother with that child seat. I will add the baggages models according to the weight of the baggage, but because our plane does not have a baggage door it can't have a cool dialog automatically open like the 182s and 172p.
