### ISSUE TITLE
Back of the propeller should be dark

### ISSUE THREAD

**Issue by gilbertohasnofb** [Harald67/c150#3]
The back side of the propeller (i.e. the side visible from the cockpit) should be dark grey or black. This is done by Cessna so there is less risk of reflections to the pilot viewpoint

![c150-4](https://cloud.githubusercontent.com/assets/5700795/17244098/68bd6dcc-5580-11e6-8647-86f4c9780f0b.jpg)

**Comment by Harald67** [comment]
I pushed a quick texture remap, but that propeller need to be redone anyway, same for the semi-transparent disk.

**Comment by gilbertohasnofb** [comment]
> but that propeller need to be redone anyway, same for the semi-transparent disk.

**Comment by gilbertohasnofb** [comment]
> but that propeller need to be redone anyway, same for the semi-transparent disk.

That's totally understandable, but shouldn’t we leave this open so we don't forget about it? This issue with the back of the propeller is a common problem with GA aircrafts in the sim and it's easy not to spot it
