### ISSUE TITLE
Coordinates for window animation are wrong

### ISSUE THREAD

**Issue by ghost** [Harald67/c150#39]
While implementing the window control via slider I noticed that the coordinates are off so on higher values it sticks into the cabin, can you change that? ;)

**Comment by gilbertohasnofb** [comment]
I do not understand what you mean, could you explain it better? What is the "window control", is it the lever that opens the windows on the doors you are talking about?

**Comment by ghost** [comment]
i added a Slider so the user can control how far it is open

---

Gesendet mit der Telekom Mail App
http://www.t-online.de/service/redir/email_app_android_sendmail_footer.htm

--- Original-Nachricht ---
Von: Gilberto Agostinho
Betreff: Re: [Harald67/c150] Coordinates for window animation are wrong 
(#39)
Datum: 12.08.2016, 14:51 Uhr
An: Harald67/c150
Cc: D-ECHO, Author

I do not understand what you mean, could you explain it better? What is the 
"window control", is it the lever that opens the windows on the doors you 
are talking about?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/Harald67/c150/issues/39#issuecomment-239437731 , or 
mute the thread

**Comment by gilbertohasnofb** [comment]
You mean you added it in that PR? Then thanks!

**Comment by ghost** [comment]
pr?

---

Gesendet mit der Telekom Mail App
http://www.t-online.de/service/redir/email_app_android_sendmail_footer.htm

--- Original-Nachricht ---
Von: Gilberto Agostinho
Betreff: Re: [Harald67/c150] Coordinates for window animation are wrong 
(#39)
Datum: 12.08.2016, 15:00 Uhr
An: Harald67/c150
Cc: D-ECHO, Author

You mean you added it in that PR? Then thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/Harald67/c150/issues/39#issuecomment-239439621 , or 
mute the thread

**Comment by ghost** [comment]
you can have a look at the code from one of the commits in the pull request

---

Gesendet mit der Telekom Mail App
http://www.t-online.de/service/redir/email_app_android_sendmail_footer.htm

--- Original-Nachricht ---
Von: Gilberto Agostinho
Betreff: Re: [Harald67/c150] Coordinates for window animation are wrong 
(#39)
Datum: 12.08.2016, 15:00 Uhr
An: Harald67/c150
Cc: D-ECHO, Author

You mean you added it in that PR? Then thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/Harald67/c150/issues/39#issuecomment-239439621 , or 
mute the thread

**Comment by gilbertohasnofb** [comment]
PR = pull request, you opened one with some code that ~~@Harold~~ @Harald67 is reviewing

**Comment by harold** [comment]
Wrong Harold, but good luck with this project. I hope it gets off the ground.

**Comment by gilbertohasnofb** [comment]
Hahaha my bad, I meant HarAld :stuck_out_tongue_closed_eyes:

**Comment by ghost** [comment]
Thanks!
