### ISSUE TITLE
Primer system

### ISSUE THREAD

**Issue by ghost** [Harald67/c150#41]
The engine can start without primer, always starts faster with primer, in cold air usually doesn't start without primer. Do you have an idea how to implement a realistic primer system?

**Comment by Harald67** [comment]
That was already done. I changed it because @gilbertohasnofb was unable to start the engine.

**Comment by gilbertohasnofb** [comment]
We could try to troubleshoot this again, though in the next days I will be super busy.

**Comment by ghost** [comment]
Is the code for this still there anywhere?

**Comment by Harald67** [comment]
The change was just:

```
@@ -200,7 +200,7 @@ var calcMixture = func(dt) {
             # up to 6 primer
         } elsif ( engineTemp <= 65 ) {
             # 1 or 2 primer
-            if( pump < 1) {
+            if( pump < 0) {
                 mixture = 0;
             }
         }

```

see bug #2

**Comment by ghost** [comment]
For me it works fine with 
`
            if( pump < 1) {`

**Comment by ghost** [comment]
@gilbertohasnofb Could you short try if it works for you if just change the thing @Harald67 wrote?

**Comment by gilbertohasnofb** [comment]
@D-ECHO I will check it now

**Comment by gilbertohasnofb** [comment]
Yes, I can start the engine fine. I really don't know what was happening before, but we can revert that and see how it goes.

**Comment by ghost** [comment]
okay, please do that and have a nice time ;)
