### ISSUE TITLE
Shorter engine start time?

### ISSUE THREAD

**Issue by ghost** [Harald67/c150#43]
And another issue ;) 
as seen in many yt videos of c150 engine startups, the time before the engine catches and runs is much lower than we have atm. Can this be changed?
Also, can the battery discharge be faster when starter is running, as it takes very much energy?

**Comment by Harald67** [comment]
I don't know how jsbsim handles the engine start, I'll have to look into the code.

The starter is not modeled yet in the electrical circuit. The battery should discharge a lot faster as soon as the started is added.

**Comment by Harald67** [comment]
Looking at jsbsim code I saw that the engine in running when rpm > 0.8 \* idle rpm, so I reduced the value of Idle rpm.
I hope that there is no side effect.

**Comment by gilbertohasnofb** [comment]
:+1: 

> I hope that there is no side effect.

Let's keep our eyes opened then.

**Comment by ghost** [comment]
As a side effect for sure the Idle rpm will be lower but as long as it's realistic

**Comment by gilbertohasnofb** [comment]
> for sure the Idle rpm will be lower

Why? Which property are you thinking about changing which would have such side effect?

**Comment by ghost** [comment]
"so I reduced the value of Idle rpm."
Harald changed the value of idle rpm so the engine starts faster, but at the same time the idle RPM will be lower, because he reduced the value of idle RPM. If the idle RPM is still realistic that's just fine.
