### ISSUE TITLE
Borrow Heading indicator and Turn Coordinator gauges from c172p

### ISSUE THREAD

**Issue by gilbertohasnofb** [Harald67/c150#5]
Borrow Heading indicator and Turn Coordinator gauges from c172p, since they are much closer to how the c150 looks in RL:

![](http://www.aviafilms.com/photos/cessna-cockpit.jpg)

![](http://s11.postimg.org/bgkjtyaab/FG_1.jpg)

But for the heading indicator, normally the c150 does not have the heading bug nor the heading bug knob, so that could be removed.

**Comment by gilbertohasnofb** [comment]
@Harald67 I noticed that we don't have a heading indicator in this model, but rather the ADF is in that position! Was this intentional? It seems to me that all pictures of the 150 cockpit show a heading indicator on that position (below the artificial horizon). 

Can I then replace the turn coordinator for the c172p's one, and the ADF for the 172's heading indicator? (I will remove the heading bug and knob from that instrument)

**Comment by gilbertohasnofb** [comment]
More photographs of cockpits showing the heading indicator always on that position:
- cockpit without ADF
  ![](http://gqwyatt.com/pictures/highres/16G-cockpit01.jpg)
- no ADF again
  ![](http://cdn-www.airliners.net/photos/airliners/7/0/0/1520007.jpg?v=v20)
- just one VOR, and the ADF is on the position of the other one
  ![](http://www.aviafilms.com/photos/cessna-150-aerobat-cockpit.jpg)
- the ADF is where our hobbs is (but htis seems to be a rare case)
  ![](http://img.wallpaperfolder.com/f/60519B752FEA/cessna-152-cockpit-150.jpg)

**Comment by Harald67** [comment]
I think we have more gauges than free slots.
So let's remove one VOR for now (and one radio) and put the ADF gauge in place of the the bottom VOR gauge.
And you can replace the turn indicator and add the heading indicator of the 172.
I'll give the option to use an ADF or a VOR later.

**Comment by gilbertohasnofb** [comment]
:+1:
