### ISSUE TITLE
Add fuel valve

### ISSUE THREAD

**Issue by Harald67** [Harald67/c150#51]
that disappeared in the remake of the c150.

![image](https://cloud.githubusercontent.com/assets/6804046/17644927/524c9802-6196-11e6-98a5-ddd773980356.png)

This is needed for the checklist.

**Comment by gilbertohasnofb** [comment]
@Harald67 do you need a texture for this?

**Comment by Harald67** [comment]
Yes, the old one was really small.
c150-int2.png :
![image](https://cloud.githubusercontent.com/assets/6804046/17657859/011f7814-62c7-11e6-9b47-8db23cfc9d6f.png)

**Comment by gilbertohasnofb** [comment]
@Harald67 Ok, so I will work on it, bur there is not much space left on `c150-int2.png`, so what if I add this texture to the `c150-obj.png`?

**Comment by Harald67** [comment]
yes, good idea.

**Comment by gilbertohasnofb** [comment]
Done, see:

![fuel selector](https://cloud.githubusercontent.com/assets/5700795/17673036/8f36a6f6-631f-11e6-9278-755728d4fb0f.png)

I based it on the following photograph:

![](http://www.holliseaster.com/gallery/d/3524-2/IMG_0410.JPG)

I added it to the `-obj.png` file and remove the older one from `-int2.png` to make space there. The modifications are already pushed in the new branch `bug-51`.

**Comment by Harald67** [comment]
Thank you !

**Comment by gilbertohasnofb** [comment]
My pleasure :wink:

**Comment by Harald67** [comment]
The valve still need to be animated.
I can't find the fuel switch property atm...

**Comment by gilbertohasnofb** [comment]
In the c172p we use `/consumables/fuel/tank[0]/selected`, which is a boolean.

**Comment by gilbertohasnofb** [comment]
Also, I have the impression the plaque with the fuel selector texture I created is too large, are you sure about its size Harald?

**Comment by Harald67** [comment]
Now that you ask, I really have no clue of its real size and I could not find any photo that could help.
How small should it be ? half size ? 3/4 of the current size ?

**Comment by gilbertohasnofb** [comment]
I also do not know exactly the size, but looking at the photograph in this https://github.com/Harald67/c150/issues/51#issuecomment-239862302 I would say it has to be around half of the current size, maybe a bit larger. See how the plaque is slightly smaller than the handle itself, so we can use that as a reference.

**Comment by gilbertohasnofb** [comment]
@Harald67 thanks for the fix, it looks much better. But I think in the OFF position the handle should be pointing down, not up.

**Comment by Harald67** [comment]
Another photo for reference.
![image](https://cloud.githubusercontent.com/assets/6804046/17802910/59bb2b24-65f3-11e6-8d29-bd4f9da9995e.png)

**Comment by gilbertohasnofb** [comment]
That's a great picture! So I think the current size we have now is fine, what do you think?

**Comment by Harald67** [comment]
yes it should be good. Since I'm doing a bit of modeling in the cabin atm I've also moved the floor step a bit backward.

**Comment by Harald67** [comment]
Isn't the handle a bit large now ?
Also note that there is a strange effect with the tooltip, it does not update correctly when changing the position of the selector.

**Comment by gilbertohasnofb** [comment]
> Isn't the handle a bit large now ?

I don't know, it looks fine to me.

> Also note that there is a strange effect with the tooltip, it does not update correctly when changing the position of the selector.

I can reproduce it here, but I don't know what is causing it. But I wanted to ask you, are you sure you can use boolean expressions such as `var fuelOn = getprop("consumables/fuel/tank[0]/selected") or getprop("consumables/fuel/tank[1]/selected");` when declaring a variable? I never seen that before. Also, we could simplify those scripts a bit since the c150 has only one single position for BOTH tanks or NEITHER tank being selected, so all these logical `or`s are not very necessary (i.e. tank[0] and tank[1] are always both selected or neither selected)

**Comment by Harald67** [comment]
> Also, we could simplify those scripts a bit since the c150 has only one single position for BOTH tanks or NEITHER tank being selected

The problem is that there is two tanks in the fuel & payload dialog and each one can be selected individually there.
