### ISSUE TITLE
Complete the checklist

### ISSUE THREAD

**Issue by Harald67** [Harald67/c150#53]
The position of the marker object is missing a few times.

**Comment by ghost** [comment]
In some checklist items there are doubles like
          `
  <name>Carburetor Heat - Cold</name>
            <value>COLD</value>
`
shall they be removed? ( changed to 
`
            <name>Carburetor Heat</name>
            <value>COLD</value>`
)

**Comment by ghost** [comment]
I fixed the doubles in 5962430
