### ISSUE TITLE
Make a 150hp version

### ISSUE THREAD

**Issue by Harald67** [Harald67/c150#57]
http://wings.esisupply.com/introduction150150.html

**Comment by ghost** [comment]
Commit 1c2c437 added a 150 hp version :D

**Comment by gilbertohasnofb** [comment]
I think the name `c150-150-set.xml` is very confusing, shouldn't we use `c150-150hp-set.xml`?

**Comment by ghost** [comment]
Okay, I'll rename it

**Comment by ghost** [comment]
Commit edd4215 renamed files.

**Comment by Harald67** [comment]
Thank, but can you make a common file with the old c150-set.xml (c150-set.xml => c150-common.xml) and include them in the new c150-set.xml and c150-150hp.xml ?

**Comment by ghost** [comment]
I made a common file, see commit 849236d
