### ISSUE TITLE
Some gauges have wrong limits

### ISSUE THREAD

**Issue by gilbertohasnofb** [Harald67/c150#6]
Some gauges have wrong limits:
- airspeed indicator: green arc should be from 40 knots until 110 knots and yellow from 110 until 150
- tachometer: green arc should range from 20 until 27, see: http://www.jacobsflightservices.com/cms-assets/images/658174.20150422113524.jpg

**Comment by gilbertohasnofb** [comment]
@Harald67 I would be happy to work on those textures and instruments if you'd like to, just let me know

**Comment by Harald67** [comment]
The old asi texture that I made 10 years ago had the correct limits but I can not find the python script that I used to create the svg file that was used to finally make the texture (see c150-instruments.rgb in Panel/Instruments/Texture)...
You can work on those textures if you like to.

**Comment by gilbertohasnofb** [comment]
> You can work on those textures if you like to.

Yes, I'd like to do that. Thanks for giving me access to the repository. And once I have the new textures, should I push them directly to the `master` branch or should we use pull requests (PRs)?

**Comment by gilbertohasnofb** [comment]
@Harald67 So I created the new RPM gauge based on the photograph I posted above, and here is how it looks in the sim:

![c150-1](https://cloud.githubusercontent.com/assets/5700795/17267400/6b76367e-5608-11e6-9f58-9ba083906d5e.jpg)

Tomorrow I will make the airspeed indicator and then push the modifications.

**Comment by gilbertohasnofb** [comment]
Actually I decided to do it right now:

![c150](https://cloud.githubusercontent.com/assets/5700795/17267505/77c3c9ca-560b-11e6-9f5c-898f4c91c105.jpg)

**Comment by Harald67** [comment]
I just saw that the rpm needle is all black, can you check that ?

**Comment by gilbertohasnofb** [comment]
Sure, I will do it right now!

**Comment by gilbertohasnofb** [comment]
Done, see the new PR
