### ISSUE TITLE
Issues with the gauges

### ISSUE THREAD

**Issue by gilbertohasnofb** [Harald67/c150#60]
I just noticed some issues with the gauges:
- blue color above all instruments (see image 1 below), is that supposed to be the glass over the gauges? If so, could we tweak this effect down a lot? I think it looks really strange
- the Attitude Indicator is too far back (see image 2)
- ~~instrument light doesn't work any more~~

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/17768625/110823dc-6535-11e6-85bb-8846e37ac79b.png)

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/5700795/17768624/11066e8e-6535-11e6-89e5-c494f41c165b.png)

**Comment by Harald67** [comment]
I'll have a look for the color problem. I don't know if it's the glass because I have a rendering problem with that glass, I thought that the strange color came from the material of the instruments (they use ambient = 1.0 instead of 0.2).

The instrument light is working fine here.

**Comment by gilbertohasnofb** [comment]
> The instrument light is working fine here.

Derp, here as well, I just had forgotten to turn on the battery :disappointed: 

> I don't know if it's the glass because I have a rendering problem with that glass, I thought that the strange color came from the material of the instruments (they use ambient = 1.0 instead of 0.2).

But have you always seen the instrument with such a bluish color? For me it started after I pulled the latest modifications today.

**Comment by Harald67** [comment]
It was really the glass, I changed the material when I was testing the sun visor.
