### ISSUE TITLE
Add a walk view?

### ISSUE THREAD

**Issue by ghost** [Harald67/c150#63]
For a preflight inspection this would be senseful, as it e.g. is for the CRJ700-family or we can add a walker as in the c172p

**Comment by Harald67** [comment]
You added the walker, but did you check that it works ? I'm not saying that there is a problem (I don't have the time to check atm), but last time I tried there were nasal bug in the configuration dialog of the walker, that's why I only added the generic pilot.

**Comment by ghost** [comment]
fir me it worked

---

Gesendet mit der Telekom Mail App
http://www.t-online.de/service/redir/email_app_android_sendmail_footer.htm

--- Original-Nachricht ---
Von: Harald JOHNSEN
Betreff: Re: [Harald67/c150] Add a walk view? (#63)
Datum: 02.09.2016, 8:32 Uhr
An: Harald67/c150
Cc: D-ECHO, Assign

You added the walker, but did you check that it works ? I'm not saying that 
there is a problem (I don't have the time to check atm), but last time I 
tried there were nasal bug in the configuration dialog of the walker, 
that's why I only added the generic pilot.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
https://github.com/Harald67/c150/issues/63#issuecomment-244294529 , or 
mute the thread

**Comment by Harald67** [comment]
Ok, the walker itself is working (or walking), thanks.
