### ISSUE TITLE
Fuel vent wrong position (was Two pitot tubes?)

### ISSUE THREAD

**Issue by ghost** [Harald67/c150#65]
It looks like there are two pitot tubes under the left wing, @Harald67 do you know what the right one is (I guess the left one is a real pitot tube?).
![fgfs-screen-036](https://cloud.githubusercontent.com/assets/12275960/18213187/3296b4be-7147-11e6-9a00-604228c0d0d4.png)

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=aCWHcDVUX38 @ 9:00 and next half minute
There seems to not be any such thing on this ac...

**Comment by gilbertohasnofb** [comment]
@D-ECHO two things:
- please embed the images at GitHub so we don't have to click on a link to see them. You can upload them directly here by clicking on the blue phrase "Attach files by dragging and dropping or selecting them" which is written under every message as we type, or you can use external links with the following code: `![](link)`, where `link` is the full url for the image
- Please try to be a bit more clear with the titles as well, as "What is this?" is really unclear. Maybe "Why are there two pitot tubes" or "Possible extra pitot tube" would be better. Same goes for commit messages and PR titles. Just think that in the future someone may pick this project up (even years for now) and then trying to figure out what we meant would be impossible

**Comment by ghost** [comment]
Okay, sorry @gilbertohasnofb

**Comment by gilbertohasnofb** [comment]
No worries! Just pointing things out :smile:

**Comment by gilbertohasnofb** [comment]
Thanks for the changes :+1:

**Comment by Harald67** [comment]
This is a fuel vent but the position is wrong ; it should behind the wing strut.

![](http://www.flyingstart.ca/FlightTraining/preflight/pitottube.jpg)
![image](https://cloud.githubusercontent.com/assets/6804046/18229708/34dfed20-7283-11e6-85a2-d5c4965e1f2d.png)

**Comment by ghost** [comment]
Yes, I also jut noted this, I will move it to the right position.

**Comment by ghost** [comment]
Was corrected in 9e85a59
