### ISSUE TITLE
Why is the volumetric shadow disabled?

### ISSUE THREAD

**Issue by ghost** [Harald67/c150#66]
Is there any specific reason why the volumentric ALS shadow is disabled? Otherwise I'd re-enable it with a correction to elevation. Also, I think the prop should not be inside the shadow, as it is unrealistic to have a standing propeller while flying ;)

**Comment by Harald67** [comment]
It was not working and the model used for the shadow is not a c150.

**Comment by ghost** [comment]
Now the shadow is working (if ALS is enabled) and are you sure this isn't a c150?
