### ISSUE TITLE
How to delete branches?

### ISSUE THREAD

**Issue by ghost** [Harald67/c150#68]
I accidently made two branches which **both** can be safely deleted, how to do so? Once that is done I will create **one** new branch with the right changes for a pull request

**Comment by gilbertohasnofb** [comment]
In the main page, there is a tab called branches and you can delete them from there, see: https://github.com/Harald67/c150/branches

**Comment by ghost** [comment]
Thanks!

Am 14.11.2016 um 09:22 schrieb Gilberto Agostinho:

**Comment by gilbertohasnofb** [comment]
My pleasure! :smile:
