### ISSUE TITLE
Compass too small

### ISSUE THREAD

**Issue by gilbertohasnofb** [Harald67/c150#7]
The compass is too small, compare this:

![](https://i.ytimg.com/vi/1NsDoEizhU0/maxresdefault.jpg)

With this:

![c150-5](https://cloud.githubusercontent.com/assets/5700795/17244325/87aed9fe-5581-11e6-9340-1ed8a6555ad7.jpg)

Also note that the compass has a cable going to the roof of the plane, which is also missing

**Comment by HHS81** [comment]
The c182s uses the same compass like shown in the first image, we have modelled it. You might wanna use it.

**Comment by gilbertohasnofb** [comment]
@HHS81 Thanks Heiko!

@Harald67 In that case I can take care of this myself :smile:

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
@Harald67 Okay, this is half done but I need your help on something. It turns out the original compass was part of the .ac model rather than having a submodel. Since I don't have the .blend file it would be better if you'd remove the old compass and export a new .ac model to the branch `bug-7` (which I already created). In that branch the new model is already correctly positioned, so once we remove the older one we can make a PR and merge it into the `master`
