### ISSUE TITLE
Cessna 152?

### ISSUE THREAD

**Issue by ghost** [Harald67/c150#71]
When the Cessna 150 is more or less well done, maybe we could add a variant, the Cessna 152. I'm not sure, does it have a different airframe? I just know it has another engine..

**Comment by gilbertohasnofb** [comment]
I believe the Cessna 152 has a different airframe, so it would be a different 3D model.

**Comment by gilbertohasnofb** [comment]
@D-ECHO I will close this as a c152 would be a different project. Besides that, awall86 is working on a great 152, though I don't know if the project is still active. See: https://forum.flightgear.org/viewtopic.php?f=4&t=27894
