### ISSUE TITLE
Still active

### ISSUE THREAD

**Issue by D-ECHO** [Harald67/c150#74]
Hey @Harald67 @gilbertohasnofb ,
first of all, I'm sorry for all the problems and confusion I created in the past due to my bad development style. Just wanted to ask whether you're both still active and up for continuing this development?

**Comment by gilbertohasnofb** [comment]
I am taking a back seat approach to FG development these days, I am really busy with RL. But I am still around, reading emails, merging a PR here and there. Happy to continue contributing to this albeit at a very slow pace if @Harald67 is still around.

**Comment by D-ECHO** [comment]
Once again returning to this, after quite some time :D

I'd like to start getting involved in this project more again, fixing the open issues and making the aircraft compatible to Compositor etc. Thus I wanted to ask, whether you both are still on it @gilbertohasnofb @Harald67, i.e. if I should make a branch for every fixed issue and await review+approval on pull requests or if you don't really care about it anymore, in that case I'd work on it more directly, possibly as a fork.

**Comment by D-ECHO** [comment]
oops, didn't want to close, just wanted to comment ;)

**Comment by gilbertohasnofb** [comment]
@D-ECHO unfortunately I am away from FlightGear at the moment, really busy with some other stuff :cry:

**Comment by D-ECHO** [comment]
... quite a while later again :D

I'm continuing development on FGAddon, hope that's fine for everyone :)
